version: '2'
services:
  my_first_nodejs-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/my_first_nodejs/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_first_nodejs
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
